<?php
/**
 * @file
 * Code for the at_slider feature.
 */

include_once 'at_slider.features.inc';

/**
 * Implements hook_entity_view_alter()
 */
function at_slider_entity_view_alter(&$build, $entity_type) {
    if ('bean' === $entity_type) {
        if (1 < count(element_children($build['slider_item']))) {
            // For debug, developer can disable the JS calls.
            if (empty($_GET['no_at_slider'])) {
                at_slider_attach_js($build);
            }
        }
    }
}

/**
 * Attach JS files & configuration for slider block.
 */
function at_slider_attach_js(&$build) {
    $lib = substr(at_library('jquery.cycle'), strlen(DRUPAL_ROOT) + 1);

    $build['#attributes']['class'][] = "slider-{$build['#entity']->delta}";
    $build['#prefix'] = '<div class="at-slider" data-delta="slider-'. $build['#entity']->delta .'">';
    $build['#suffix'] = '</div>';

    $build['#attached']['js'] = array(
      $lib . '/jquery.cycle.all.min.js',
      drupal_get_path('module', 'at_slider') . '/misc/js/slider.js',
      array('type' => 'setting', 'data' => array('at_slider' => array(
        $build['#entity']->delta => at_slider_get_js_options($build['#entity'])
      ))),
    );
}

/**
 * Build Javascript options for bean-slider.
 *
 * Options:
 *
 * - %delta: {}
 * - default: {}
 *
 * Sample options can be found at: http://jquery.malsup.com/cycle2/api/#options
 */
function at_slider_get_js_options($bean) {
    $config = at_container('helper.config_fetcher')
      ->getItems('at_slider', 'slider_options', 'options');

    if (isset($config[$bean->delta])) {
        return $config[$bean->delta];
    }

    if (isset($config['default'])) {
        return $config['default'];
    }

    return array(
      'speed' => 600,
    );
}
